# Generated by Django 3.2.6 on 2021-08-22 01:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('photologue', '0011_auto_20190223_2138'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhotoExtended2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('captiona', models.TextField(blank=True, null=True, verbose_name='Caption1')),
                ('captionb', models.TextField(blank=True, null=True, verbose_name='Caption2')),
                ('photo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='extended', to='photologue.photo')),
            ],
            options={
                'verbose_name': 'Extra fields',
                'verbose_name_plural': 'Captions and Tags',
            },
        ),
        migrations.CreateModel(
            name='GalleryExtended',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gallery', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='extended', to='photologue.gallery')),
            ],
            options={
                'verbose_name': 'Extra fields',
                'verbose_name_plural': 'Extra fields',
            },
        ),
    ]
